export const START_NEW_GAME = "START_NEW_GAME";

export const FETCH_BREEDS = "FETCH_DOGGOS";

export const FETCH_DOGGOS = "FETCH_DOGGOS";

export const PREPARE_PAIRS = "PREPARE_PAIRS";

export const SET_USER_SCORE = "SET_USER_SCORE";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_MATCHED_PAIR = "SET_MATCHED_PAIR";
